#!/usr/bin/env bash
# One-time WiFi pairing with an Android device.
# After pairing, saves the device IP and debug port to .wifi-device for future use.
#
# Usage: ./scripts/wifi-pair.sh <pairing_ip:port> <pairing_code> <debug_port>
#
# Example:
#   ./scripts/wifi-pair.sh 192.168.77.123:36401 622424 42951
#
# The pairing IP:port and code are shown on the phone under:
#   Settings > Developer options > Wireless debugging > Pair device with pairing code
# The debug port is shown on the main Wireless debugging screen (IP address & Port).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_DIR/.wifi-device"
ADB="${ADB:-adb}"

if [ $# -lt 3 ]; then
    echo "Usage: $0 <pairing_ip:port> <pairing_code> <debug_port>"
    echo ""
    echo "Example: $0 192.168.77.123:36401 622424 42951"
    echo ""
    echo "On your phone, go to:"
    echo "  Settings > Developer options > Wireless debugging"
    echo "  - Debug port: shown under 'IP address & Port'"
    echo "  - Tap 'Pair device with pairing code' for pairing IP:port and code"
    exit 1
fi

PAIR_ADDRESS="$1"
PAIR_CODE="$2"
DEBUG_PORT="$3"

# Extract IP from pairing address
DEVICE_IP="${PAIR_ADDRESS%%:*}"

echo "Pairing with device at $PAIR_ADDRESS..."
$ADB pair "$PAIR_ADDRESS" "$PAIR_CODE"

echo ""
echo "Saving WiFi device config to .wifi-device..."
cat > "$CONFIG_FILE" <<EOF
# WiFi device configuration (auto-generated by wifi-pair.sh)
DEVICE_IP=$DEVICE_IP
DEBUG_PORT=$DEBUG_PORT
EOF

echo "Saved: IP=$DEVICE_IP, debug port=$DEBUG_PORT"
echo ""

# Try connecting immediately
echo "Connecting to $DEVICE_IP:$DEBUG_PORT..."
$ADB connect "$DEVICE_IP:$DEBUG_PORT"

echo ""
echo "Device paired and connected. You can now use --wifi with install/deploy scripts."
